name: e2e testing

on:
  workflow-dispatch:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $deafult-branch ]

jobs:
  cypress:
    defaults:
      run:
        working-directory: ../

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      
      - run: npm install

      - run: npm run build
        env:
          NODE_ENV: production
      
      - name: Run project locally
        run:
          npm install serve
          $(npm bin)/serve dist -s -p 30000 &
      
      - name: Run tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ../
          browser: chrome
          headless: true